### ISSUE TITLE
selector order gone wrong

### ISSUE THREAD

**Issue by Fatmylin** [khiav223577/texture_packer#14]
### Summary
- When a image has active, hover statuses at desktop, and only active status at mobile. It will make active front of hover leading hover selector broken

### Symptom
- in packed.css:
```css
.tab {width:132px; height:64px; background-position: -853px -133px}
.tab:hover {width:132px; height:64px; background-position: -853px -67px}
.tab:active {width:132px; height:64px; background-position: -853px -1px}
```

- in packed_m.css:
```css
.tab-active-m {width:132px; height:64px; background-position: -853px -133px}
.tab-m{width:132px; height:64px; background-position: -853px -1px}
```

- in packed.scss:
```scss
@mixin common_ui_ocean_tab{ width:132px; height:64px; background-position: -853px -133px; &:active, &.active{ width:132px; height:64px; background-position: -853px -1px; @include mobile{ width:110px; height:52px; background-position: -1px -752px; } }@include mobile{ width:110px; height:52px; background-position: -113px -752px; }&:hover, &.hover{ width:132px; height:64px; background-position: -853px -67px; } }
```
